batch_size: 16
cache: true
device: cuda
epochs: 100
label_smoothing: 0
model: ViT
num_workers: 0
optimizer: RMSprop
optimizer_hyp:
  lr: 0.0001
  weight_decay: 1.0e-05
path_test: Datasets\Folds\TrainAll\Test
path_train: Datasets\Folds\TrainAll\Train
patience: 10
pin_memory: true
save_dir: experiments\ViT_B_32_ENSEMBLE_FINAL\ensemble_9
seed: 8675309
soft_label: None
