batch_size: 64
cache: true
device: cuda
epochs: 100
label_smoothing: 0
model: ViT
num_workers: 0
optimizer: AdamW
optimizer_hyp:
  lr: 0.0001
  weight_decay: 1.0e-05
path_test: Datasets\Folds\4\Test
path_train: Datasets\Folds\4\Train
patience: 10
pin_memory: true
scheduler: CosineAnnealingLR
scheduler_hyp:
  T_max: 20
  eta_min: 1.0e-06
soft_label: step
