# config_NCNN.yaml

# Model to be trained
model: NCNN
# Dataset path
path_train: 'Datasets\Folds\0\Train'
path_test: 'Datasets\Folds\0\Test'
# Device configuration
device: 'cuda'
cache: False
pin_memory: True
num_workers: 4
# Training Hyperparameters
epochs: 120
patience: 43
batch_size: 16
soft_label: False
label_smoothing: 0.3
optimizer: RMSprop
optimizer_hyp:
  lr: 0.0001
  weight_decay: 0.00001
scheduler: CosineAnnealingLR
scheduler_hyp:
  T_max: 5
  eta_min: 0.000001








