# config_NCNN.yaml

# Model to be trained
model: NCNN
# Dataset path
path_train: 'Datasets\Folds\0\Train'
path_test: 'Datasets\Folds\0\Test'
# Device configuration
device: 'cuda'
cache: True
pin_memory: True
num_workers: 0
# Training Hyperparameters
epochs: 120
patience: 43
batch_size: 16
soft_label: 'None'
label_smoothing: 0.3
optimizer: RMSprop
optimizer_hyp:
  lr: 1.0e-03
  weight_decay: 1.0e-05
scheduler: CosineAnnealingLR
scheduler_hyp:
  T_max: 5
  eta_min: 1.0e-06








