batch_size: 16
cache: true
device: cuda
epochs: 100
label_smoothing: 0
model: NCNN
num_workers: 0
optimizer: RMSprop
optimizer_hyp:
  lr: 0.0001
  weight_decay: 1.0e-05
path_test: Datasets\Folds\TrainAll\Test
path_train: Datasets\Folds\TrainAll\Train
patience: 10
pin_memory: true
save_dir: experiments/NCNN_FINAL
seed: 1234
soft_label: None
