# config_VGGNB.yaml

# Model to be trained
model: VGGNB
# Dataset path
path_train: 'Datasets\Folds\0\Train'
path_test: 'Datasets\Folds\0\Test'
# Device configuration
device: 'cuda'
cache: True
pin_memory: True
num_workers: 0
# Training Hyperparameters
epochs: 50
patience: 5
batch_size: 16
soft_label: False
label_smoothing: 0
optimizer: RMSprop
optimizer_hyp:
  lr: 0.00001
  weight_decay: 0.00001








